version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
    

jobs:
  test-api:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: coverage run test_roll.py
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t 73691f3c-2ece-44bd-8c9c-3ecbe0a20887





workflows:
  version: 2.
  build-test:
    jobs:
      - test-api
